name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v3

      - name: Get code
        run: |
          echo ${{ toJSON(github) }}
          git clone https://github.com/${{ github.repository }}.git


